RECORD_NOT_FOUND_ERROR_CODE = 1000;
RECORD_NOT_FOUND_ERROR_DESCRIPTION = "DATABASE RECORD NOT FOUND WITH ATTRIBUTES: ";
MISSING_REQUIRED_PARAM_ERROR_CODE = 1001;
MISSING_REQUIRED_PARAM_ERROR_DESCRIPTION = "THE FOLLOWING REQUIRED PARAM IS MISSING: ";


FAILED_TO_CREATE_TEAM_ERROR_CODE = 2000;
FAILED_TO_CREATE_TEAM_ERROR_DESCRIPTION = "TEAM FAILED TO BE CREATED WITH PARAMS: ";
FAILED_TO_UPDATE_TEAM_ERROR_CODE = 2001;
FAILED_TO_UPDATE_TEAM_ERROR_DESCRIPTION = "TEAM FAILED TO BE UPDATED WITH PARAMS: ";
